# Safe-restart Jenkins
- name: Restart Jenkins
  become: yes
  command: "{{ jenkins_cli_cmd }} safe-restart --username {{ jenkins_admin_user }} --password-file {{ jenkins_admin_password_file }}"
  when: jenkins_admin_user is defined and jenkins_admin_password_file is defined
